### ISSUE TITLE
Smith crashes upon paste when clipboard is empty

### ISSUE THREAD

**Issue by matthias-t** [IGI-111/Smith#11]
How to reproduce:
- reboot
- edit a file with Smith
- <kbd>Ctrl</kbd> + <kbd>v</kbd>

OS: `Arch Linux x86_64`

**Comment by matthias-t** [comment]
So I forked the repo and updated the dependencies, making the necessary fixes for API changes. Strangely, the handling of text selection got noticeably slower.

**Comment by IGI-111** [comment]
That is quite strange, but it might have to do with updates to underlying libs like ropey more than just the clipboards.

I'll take a look.

**Comment by IGI-111** [comment]
Should be fixed in the update. Do reopen if you still encounter the problem.
