### ISSUE TITLE
Text selection is very slow

### ISSUE THREAD

**Issue by matthias-t** [IGI-111/Smith#15]
~~Since the `ropey` and `clipboard` crates were updated, text selection is noticeably slower (try moving around a bit with the mouse button down).~~ I noticed that Smith redraws after handling every single event. ~~Could that be the cause?~~
https://github.com/IGI-111/Smith/blob/1f8e4906bdae0bd86684f58b079b983430e6aa20/src/main.rs#L42-L50

**Comment by IGI-111** [comment]
Yes, Smith is immediate mode. So you might experience stuttering, although the release build should be fine.

This is more of a placeholder than any real design decision, if you know any clever rendering tricks i'm all ears.

Besides just caching the output which is done already, I guess bailing on outdated rendering would be good, but i'm not sure how to implement that.

**Comment by matthias-t** [comment]
Whoops, I might have compared the release build of the old version and the debug build of the new one with updated dependencies.

**Comment by IGI-111** [comment]
I guess that's why i can only reproduce on debug.

I'm closing this, but rendering speed does have ways to go, so I might look into it anyway.
