### ISSUE TITLE
libxcb.so dependency on Ubuntu

### ISSUE THREAD

**Issue by stevedonovan** [IGI-111/Smith#23]
I had to install the package xcb first, and then do the usual symlink dance from libxcb.so.1.1.0 to libxcb.so for the linker to pick it up.  (For some reason, Debian/Ubuntu no longer provide the unadorned symlink in place).  Then happiness happened.

Unfortunately does not understand shift-arrow to mean selection.....

**Comment by keith-hall** [comment]
I also had some problems building `Smith` on Ubuntu 18.04, I got some super cryptic error messages like:
```
  = note: /usr/bin/ld: cannot find -lxcb-xfixes
          collect2: error: ld returned 1 exit status
```

I had no idea what an `-lxcb-xfixes` was, but managed to resolve it with:

```sh
sudo apt-get install xcb libxcb-render-util0-dev libxcb-shape0-dev libxcb-xfixes0-dev
```

**Comment by IGI-111** [comment]
Added some message about the libraries one might need to install. Closing this.
