### ISSUE TITLE
Delete Key

### ISSUE THREAD

**Issue by jackpot51** [IGI-111/Smith#3]
The delete key does not work. In termion this is `Key::Delete`

**Comment by IGI-111** [comment]
Got it added, thanks for the suggestion.

**Comment by jackpot51** [comment]
@IGI-111 delete should remove the character in front of the cursor, not behind

**Comment by IGI-111** [comment]
Yeah I kinda overlooked it since I don't use the delete key that much myself. It's behaving as intended now.

**Comment by jackpot51** [comment]
cool
