### ISSUE TITLE
Strange behaviour on tab when opening file

### ISSUE THREAD

**Issue by detly** [IGI-111/Smith#30]
I launched Smith (v1.3.0 installed via Cargo on Ubuntu 19.10), and used <kbd>ctrl</kbd>+<kbd>o</kbd> to get the prompt to open a file. I thought I'd see if i could get path suggestion/completion on pressing <kbd>tab</kbd> and instead got a line break inside the prompt, and some strange highlighting behaviour. See attached gif.

I'd expect (if <kbd>tab</kbd> isn't going to do completion) either a literal tab to be inserted, or simply nothing to happen.

![smithtabs](https://user-images.githubusercontent.com/311239/86683742-33a5c600-c045-11ea-977a-88eaaf86cada.gif)

**Comment by IGI-111** [comment]
Alright so this is fixed in 2.0, tab is specifically without effect in the prompt.
I'm keeping your suggestion for file completion of course.
