### ISSUE TITLE
AUR package is broken

### ISSUE THREAD

**Issue by deathtrip** [IGI-111/Smith#32]
The [AUR package](https://aur.archlinux.org/packages/smith/) wasn't updated in a long time, and now it's missing an upstream URL and even the source. So it's basically useless, as it won't even build. You should consider switching the package to git, as the repo has no tagged releases.

**Comment by IGI-111** [comment]
I just checked it out, besides the version number being out of date the AUR package works just fine. I tried manual install and through yay, it's all working fine on my system.

It is just deferring the build to cargo install though, which is one of the methods you can find in the [guidelines](https://wiki.archlinux.org/index.php/Rust_package_guidelines#Notes_about_using_cargo_install). So you'll always get the latest build from crates.io if you run the PKGBUILD.

I will update the version number though, probably should have done so a while ago.
