### ISSUE TITLE
Clear screen on exit

### ISSUE THREAD

**Issue by Shadlock0133** [IGI-111/Smith#4]
Exiting smith with ctrl+q leaves garbage on terminal.

**Comment by IGI-111** [comment]
This is due to a limitation in termion, but [this](https://github.com/ticki/termion/pull/66) should fix it.

**Comment by Shadlock0133** [comment]
I think that it can just clear screen instead of restoring old one. At least for now. Thanks for quick response.

**Comment by IGI-111** [comment]
I did end up putting in screen restoration, although manually using the alternate screen codes.

**Comment by Shadlock0133** [comment]
Works great. Thanks. I will probably use it as alternative to nano.
