### ISSUE TITLE
Panic on single-line files without line terminators

### ISSUE THREAD

**Issue by xTibor** [IGI-111/Smith#7]
Found this bug while playing with Redox. When I open a single-line file without any line terminator, the editor shows a blank document. Pressing a down arrow then causes the program to panic with the following message:

`thread 'main' panicked at 'Rope::line_index_to_char_index(): attempted to index beyond the end of the text.', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ropey-0.3.0/src/lib.rs:273`

**Comment by IGI-111** [comment]
Thanks for the feedback, should be easy enough to fix.
