### ISSUE TITLE
Update to latest Ropey

### ISSUE THREAD

**Issue by cessen** [IGI-111/Smith#9]
Hello!  I've recently released a much better (faster, lower memory overhead, properly documented and tested, etc.) version of [Ropey](https://github.com/cessen/ropey).

I took a crack at updating Smith to use it, and it was pretty straight-forward:
https://gist.github.com/cessen/cf15ab9384f7439d8637585f401ddb7f

Can't guarantee that I got everything right (I didn't thoroughly examine your code base), but it compiles and appears to work correctly on the files I tested.

**Comment by IGI-111** [comment]
I'll most certainly check it out. Thanks.
